# Generated by Django 5.1.1 on 2024-11-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='projects/default_project_image.jpg', null=True, upload_to='projects/'),
        ),
    ]
